name: cronet_grpc
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.1.2
  grpc:
    path: ../grpc-dart
  http2: ^2.0.0


dev_dependencies:
  ffigen: ^2.4.2
  test: ^1.16.0
