name: cronet_grpc
version: 0.0.1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  ffi: ">=1.2.1<2.0.0"
  grpc:
    path: ../grpc-dart
  http2: ^2.0.0


dev_dependencies:
  ffigen: ">=5.0.0<6.0.0"
  test: ">=1.21.1<2.0.0"
